**Task 1 - Web Scraping Quotes Website**
  
Internship - CodeAlpha Data Analytics  
Author - Aniket Mishra  
Student ID - CA/DF1/207077

**Objective** -

The objective of this project is to use python library like BeautifulSoup to extract data from a public website, identify and collect relevant data from web pages, understand the HTML structure and web navigation to gather accurate data and create a custom dataset for further analysis.

**Understanding the Website** -

The website used in this project is https://quotes.toscrape.com/. It's a practice website designed for learning web scraping techniques. It contains famous quotes from different authors. It includes three pieces of information that is, the quote itself, author's name and tags.  
The quotes are distributed across multiple pages, with 10 quotes on each page. This structure makes the website suitable for practicing page navigation and data extraction.

In [1]:
# Importing libraries

import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
# Loading and checking the website

website_url = "https://quotes.toscrape.com/"

response = requests.get(website_url)
print(response.status_code)

200

**Observation** -

Status code 200 means the website was downloaded successfully.

In [3]:
# Parsing HTML

soup = BeautifulSoup(response.text,"html.parser")

**Observation** -

`BeautifulSoup` module converts the HTML into a format that Python can easily search.

In [4]:
# Extracting container

quotes = soup.find_all("div", class_= "quote")

print(len(quotes))

10

**Observation** -

The `find_all()` function searches the HTML page and finds all `<div>` elements with the class name `quote` , whereas, the `len()` function counts the total number of quote containers found on the current page.    
The first page contains 10 quotes. Each quote is stored inside.

In [5]:
# Creating empty list

all_quotes = []

**Observation** -

An empty list named `all_quotes` is created to store the scraped data.

In [6]:
# Scraping data 

page_number = 1
while True:
    
    website_url = f"https://quotes.toscrape.com/page/{page_number}/"
    response = requests.get(website_url)
    
    if response.status_code != 200 :
        break

    soup = BeautifulSoup(response.text, "html.parser")
    quotes = soup.find_all("div", class_= "quote")

    if len(quotes) == 0 :
        break

    for quote in quotes :

        quotations = quote.find("span", class_= "text").text
        authors = quote.find("small", class_= "author").text
        tags = ", ".join([t.text for t in quote.find_all("a", class_= "tag")])

        all_quotes.append([quotations, authors, tags])

    page_number += 1

**Observation** -

The scraper starts from page 1 and downloads each webpage using the `requests` library. BeautifulSoup parses the HTML and finds all quote sections using the `<div class = "quote">` tag.  
For each quote on the webpage, the program extracts three pieces of information :  
1. Quote Text : The actual quote, stored inside the `<span class="text">` element.  
2. Author Name : The name of the author, stored inside the `<small class="author">` element.  
3. Tags : The keywords related to the quote, stored inside one or more `<a class="tag">` elements.
   
The extracted quote, author, and tags are then added to the `all_quotes` list. After all pages have been scraped, this list contains the complete dataset and is ready to be converted into a pandas DataFrame.  
After completing one page, the scraper automatically moves to the next page. The process continues until there are no more pages to scrape. At that point, the loop stops automatically.

In [7]:
print(len(all_quotes))

100

**Observation** -

The website contains 100 quotes in total. All quotes have now been collected.

In [8]:
# Creating pandas dataframe

df = pd.DataFrame(all_quotes, columns = ["Quote", "Author", "Tags"])
df.head()

,Quote,Author,Tags
0,“The world as we have created it is a process ...,Albert Einstein,"change, deep-thoughts, thinking, world"
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,"abilities, choices"
2,“There are only two ways to live your life. On...,Albert Einstein,"inspirational, life, live, miracle, miracles"
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,"aliteracy, books, classic, humor"
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"be-yourself, inspirational"

**Observation** -

A dataframe has been created. We can see the first five rows.

In [9]:
df.tail()

,Quote,Author,Tags
95,“You never really understand a person until yo...,Harper Lee,better-life-empathy
96,“You have to write the book that wants to be w...,Madeleine L'Engle,"books, children, difficult, grown-ups, write, ..."
97,“Never tell the truth to people who are not wo...,Mark Twain,truth
98,"“A person's a person, no matter how small.”",Dr. Seuss,inspirational
99,“... a mind needs books as a sword needs a whe...,George R.R. Martin,"books, mind"

**Observation** -

The last five rows of the dataset have been displayed and we can see that the data has been scraped successfully until the last page of the website.

In [10]:
# Saving the dataset

df.to_csv("Quotes.csv", index = False)

print("CSV file saved successfully.")

CSV file saved successfully.

**Observation** -

The scraped data is saved into a CSV file named `Quotes.csv`. This dataset can now be used for EDA and visualization.

**Conclusion** -

1. In this project, data was successfully scraped from https://quotes.toscrape.com using python and BeautifulSoup.   
2. The dataset include three fields : quotes, author's name and tags.  
3. Inspected the HTML structure and identify the required elements using HTML tags and class names.  
4. Page navigation was used to scrape quotes from all pages of the website automatically.  
5. A total of 100 quotes were collected and saved into a CSV file named `Quotes.csv`.   
6. A structured dataset was created and saved as `Quotes.csv` for future analysis.